---
- hosts: localhost
  gather_facts: no
  become: yes

  vars:
    image_name: "test"
    image_tag: "0.1"
    listen_port: "5000"
    exposed_port: "5000"

  tasks:
    - name: Create code/ DIR
      file:
        dest: code/
        state: directory

    - name: Get latest application code from GitHub
      git:
        repo: https://github.com/teodor-varbanov/DevOps-Training.git
        version: main
        dest: code/
        force: true
      environment:
        GIT_TERMINAL_PROMPT: 0 
    
    - name: Build container image
      docker_image:
        name: "{{ image_name }}:{{ image_tag }}"
        source: build
        build:
          path: /home/dodo/DevOps [Telerik]/DevOps-Training/Ansible homework/code/Docker exercises
        state: present

    - name: Run Docker container
      docker_container:
        name: "{{ image_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        detach: true
        ports:
          - "{{ exposed_port }}:{{ listen_port }}"